FILA_NORMAL = "NM"
FILA_PRIORITARIA = "PR"

VALOR_PADRAO_MAXIMO = 200
VALOR_PADRAO_MINIMO = 0

TIPO_FILA_NORMAL = "normal"
TIPO_FILA_NORMAL_NM = "nm"
TIPO_FILA_PRIORITARIA = "prioritaria"
TIPO_FILA_PRIORITARIA_PR = "pr"

TIPO_FILA_DISPONIVEL = [TIPO_FILA_PRIORITARIA, TIPO_FILA_PRIORITARIA_PR, TIPO_FILA_NORMAL, TIPO_FILA_NORMAL_NM]
